typography_spectrum: 0.74399
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#a90b0f'
    - '#6f6f6f'
    - '#9f9f9f'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.75
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99972
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Greg Fulcher
  email: greg@1013media.com
name: 1013media
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 1013media
content: []
description: 'voodoo-free, full-service media production'
purpose:
  - type: contact
    url: 'tel:415.508.6766'
    label: 'phone: 415.508.6766'
  - type: contact
    url: 'mailto:info@1013media.com'
    label: 'email:'
