name: 1013media BETA
favicon: null
layout_spectrum: 0.99972
typography_spectrum: 0.74399
title: '1013media - voodoo-free, full-service media production'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#a90b0f'
    - '#6f6f6f'
    - '#9f9f9f'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
