name: 1013media BETA
favicon: null
layout_spectrum: 0.10932014882564545
typography_spectrum: 0.7545722036156803
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.14881751104258
  lightness: 0.30060215946286917
  saturation: 0.8713972175028175
  rhythmicContrast: 0.8775532650761306
purpose: []
